// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastGameState(arg1) {
  return window['go']['main']['App']['BroadcastGameState'](arg1);
}

export function CreatePlayer(arg1) {
  return window['go']['main']['App']['CreatePlayer'](arg1);
}

export function DeleteDraftModifier(arg1) {
  return window['go']['main']['App']['DeleteDraftModifier'](arg1);
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetDraftModifiers() {
  return window['go']['main']['App']['GetDraftModifiers']();
}

export function ListPlayers() {
  return window['go']['main']['App']['ListPlayers']();
}

export function ResetCharacterStats(arg1) {
  return window['go']['main']['App']['ResetCharacterStats'](arg1);
}

export function SaveDraftModifier(arg1) {
  return window['go']['main']['App']['SaveDraftModifier'](arg1);
}

export function StartLanServer() {
  return window['go']['main']['App']['StartLanServer']();
}

export function StopLanServer() {
  return window['go']['main']['App']['StopLanServer']();
}

export function UpdateCharacterStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCharacterStats'](arg1, arg2, arg3);
}
