// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function BroadcastGameState(arg1:string):Promise<void>;

export function CreatePlayer(arg1:string):Promise<store.Player>;

export function DeleteDraftModifier(arg1:string):Promise<void>;

export function GetCharacters():Promise<Array<store.Character>>;

export function GetDraftModifiers():Promise<Array<store.DraftModifier>>;

export function ListPlayers():Promise<Array<store.Player>>;

export function ResetCharacterStats(arg1:number):Promise<void>;

export function SaveDraftModifier(arg1:store.DraftModifier):Promise<void>;

export function StartLanServer():Promise<Record<string, string>>;

export function StopLanServer():Promise<void>;

export function UpdateCharacterStats(arg1:number,arg2:number,arg3:number):Promise<void>;
